### ISSUE TITLE
server-side errors - baseErrors should be defined in the controller

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#348] opened 2018-10-28 10:48 UTC
On page 309 of the book when displaying a server-side validation error in `sign-up.js` controller, it is not clear where the variable `baseErrors` comes from in the following code-snippet:
```
// app/controllers/sign-up.js
import extractServerError from 'rarwe/utils/extract-server-error';

export default Controller.extend({
....
actions: {
  async signUp(event) {
    event.preventDefault();
    await this.model.save();
    await this.transitionToRoute('login'); try {
    await this.model.save();
    await this.transitionToRoute('login'); } catch(response) {
    let errorMessage = extractServerError(response.errors);
    this.baseErrors.pushObject(errorMessage);
  }
}
```
The same is for how to display `baseErrors` in the template as there is no code to demonstrate it in work.

**Comment by balinterdi** [comment] 2018-10-29 13:28
This is a duplicate of https://github.com/balinterdi/rarwe-issues/issues/342 and is already fixed in the book. It will go out with the next release (that is somewhat delayed because there are a few overarching changes introduced to Ember that I want to apply in the book – like angle-bracket invocation).

**Closed** 2018-11-21 09:17 UTC
Labels: duplicate, fixed
